
name: terraform plan

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - "**.tf"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  # ... lint removed for brevity
  plan:
    name: Plan
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        path:
          - terraform/main/resources/IT
          - terraform/main/resources/Sales

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9

      - name: Initialize Terraform
        id: init
        run: |
          cd ${{ matrix.path }}
          terraform init -input=false          

      - name: Plan Terraform
        id: plan
        continue-on-error: true
        run: |
          cd terraform/${{ matrix.path }}
          terraform plan -input=false -no-color          

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization \`${{ steps.init.outcome }}\`
            #### Terraform Plan \`${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}\`

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
